spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://localhost:3306/tcc?characterEncoding=UTF-8
    username: root
    password: rootroot
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  dubbo:
    application:
      name: application-account
    protocol:
      name: dubbo
      port: 20881
    registry:
      address: zookeeper://localhost:2291
    scan: com.huang
jdbc:
  url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8